/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javax_comm_RXTXCommDriver */

#ifndef _Included_javax_comm_RXTXCommDriver
#define _Included_javax_comm_RXTXCommDriver
#ifdef __cplusplus
extern "C" {
#endif
#undef javax_comm_RXTXCommDriver_debug
#define javax_comm_RXTXCommDriver_debug 0L
#undef javax_comm_RXTXCommDriver_devel
#define javax_comm_RXTXCommDriver_devel 0L
/* Inaccessible static: noVersionOutput */
/*
 * Class:     javax_comm_RXTXCommDriver
 * Method:    registerKnownPorts
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_javax_comm_RXTXCommDriver_registerKnownPorts
  (JNIEnv *, jobject, jint);

/*
 * Class:     javax_comm_RXTXCommDriver
 * Method:    isPortPrefixValid
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_javax_comm_RXTXCommDriver_isPortPrefixValid
  (JNIEnv *, jobject, jstring);

/*
 * Class:     javax_comm_RXTXCommDriver
 * Method:    testRead
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_javax_comm_RXTXCommDriver_testRead
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     javax_comm_RXTXCommDriver
 * Method:    getDeviceDirectory
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_javax_comm_RXTXCommDriver_getDeviceDirectory
  (JNIEnv *, jobject);

/*
 * Class:     javax_comm_RXTXCommDriver
 * Method:    nativeGetVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_javax_comm_RXTXCommDriver_nativeGetVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
